steps:
  - name: Update Composer
    command: '/usr/local/bin/composer self-update'
  - name: Install drush-master for d8
    command: 'composer global require drush/drush ; drush --version'
  - name: Run the profile script
    command: 'chmod +x ./$SRC_DIR/.probo-profile-build.sh ; ./$SRC_DIR/.probo-profile-build.sh'
  - name: Run install
    command: "drush site-install --root=/var/www/html lightning --db-url='mysqli://root:strongpassword@localhost/lightning'"
  - name: Set file directory permissions
    command: 'chown -R www-data:www-data /var/www/html/sites/default/files'
  - name: Rebuild caches
    command: 'drush cr'
  - name: Run behat tests
    command: 'cd /var/www/html/profiles/lightning/tests ; composer install ; ./bin/behat --profile probo'
